// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6daUKYkEiGZbEmm-cQBcNmwVs522ZliU',
    appId: '1:1031331266290:web:256813e7a4510bf347da6b',
    messagingSenderId: '1031331266290',
    projectId: 'foqusapp-9b096',
    authDomain: 'foqusapp-9b096.firebaseapp.com',
    storageBucket: 'foqusapp-9b096.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-84Ra7d4okiXEy8ijF0OtSYrhpOneA9Q',
    appId: '1:1031331266290:android:40f605a07172763d47da6b',
    messagingSenderId: '1031331266290',
    projectId: 'foqusapp-9b096',
    storageBucket: 'foqusapp-9b096.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ0qTS99cLAKmj3zcPXUuQMFGsQHRM3Og',
    appId: '1:1031331266290:ios:6f6b78d668b878e547da6b',
    messagingSenderId: '1031331266290',
    projectId: 'foqusapp-9b096',
    storageBucket: 'foqusapp-9b096.firebasestorage.app',
    iosBundleId: 'com.example.foqusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ0qTS99cLAKmj3zcPXUuQMFGsQHRM3Og',
    appId: '1:1031331266290:ios:6f6b78d668b878e547da6b',
    messagingSenderId: '1031331266290',
    projectId: 'foqusapp-9b096',
    storageBucket: 'foqusapp-9b096.firebasestorage.app',
    iosBundleId: 'com.example.foqusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6daUKYkEiGZbEmm-cQBcNmwVs522ZliU',
    appId: '1:1031331266290:web:53aacfc30392695847da6b',
    messagingSenderId: '1031331266290',
    projectId: 'foqusapp-9b096',
    authDomain: 'foqusapp-9b096.firebaseapp.com',
    storageBucket: 'foqusapp-9b096.firebasestorage.app',
  );
}
